#!/usr/bin/env python3
"""Pre-compress the web UI text assets (HTML/CSS/JS) into gzipped PROGMEM byte
arrays, so the scanner serves them with `Content-Encoding: gzip` (~70% smaller).

Runs as a PlatformIO `pre:` build hook. The readable source of truth stays in
src/*HTML.h / src/Shared*.h (edit those); this script parses each
`const char NAME[] PROGMEM = R"..."` declaration — reconstructing the
FIRMWARE_VERSION splices the same way the C compiler concatenates them — gzips
the result, and writes one generated header, src/gen/WebAssetsGz.h.

The generated header is git-ignored and rewritten only when its content
changes, so unchanged assets don't trigger a recompile.

Can also be run standalone for inspection:  python3 scripts/gen_gzip_assets.py
(reads the version from platformio.ini's -DFIRMWARE_VERSION flag).
"""

import gzip
import os
import re
import sys

# PlatformIO execs this via SCons without a __file__ binding; in that context
# the build's working directory is the project root.
try:
    PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
except NameError:
    PROJECT_DIR = os.getcwd()
SRC_DIR = os.path.join(PROJECT_DIR, "src")
GEN_DIR = os.path.join(SRC_DIR, "gen")
OUT_HEADER = os.path.join(GEN_DIR, "WebAssetsGz.h")

# Only `const char NAME[] PROGMEM = R"..."` string assets are gzipped. The logo
# arrays are `static const uint8_t ... = { ... }` (already-compressed PNG/JPEG)
# and don't match this pattern, so they're left alone.
DECL_RE = re.compile(r"const\s+char\s+([A-Za-z_][A-Za-z0-9_]*)\s*\[\]\s*PROGMEM\s*=\s*")


def reconstruct_literal(text, start, version):
    """Walk the C string-concatenation expression after `... = ` and return the
    logical bytes: raw-string literals contribute their inner content, bare
    `FIRMWARE_VERSION` tokens contribute the version string."""
    i = start
    n = len(text)
    parts = []
    while i < n:
        c = text[i]
        if c.isspace():
            i += 1
            continue
        if c == ";":
            break
        if text.startswith("FIRMWARE_VERSION", i):
            parts.append(version)
            i += len("FIRMWARE_VERSION")
            continue
        if c == "R" and i + 1 < n and text[i + 1] == '"':
            open_paren = text.index("(", i + 2)
            delim = text[i + 2:open_paren]
            closer = ")" + delim + '"'
            end = text.index(closer, open_paren + 1)
            parts.append(text[open_paren + 1:end])
            i = end + len(closer)
            continue
        raise ValueError(
            "unexpected token building asset near: %r" % text[i:i + 24]
        )
    return "".join(parts)


def collect_assets(version):
    """Return [(NAME, gzipped_bytes), ...] for every string asset in src/*.h."""
    assets = []
    for fname in sorted(os.listdir(SRC_DIR)):
        if not fname.endswith(".h"):
            continue
        path = os.path.join(SRC_DIR, fname)
        with open(path, "r", encoding="utf-8") as fh:
            text = fh.read()
        for m in DECL_RE.finditer(text):
            name = m.group(1)
            content = reconstruct_literal(text, m.end(), version)
            gz = gzip.compress(content.encode("utf-8"), compresslevel=9, mtime=0)
            assets.append((name, gz))
    return assets


def render_header(assets, version):
    lines = [
        "#pragma once",
        "// AUTO-GENERATED by scripts/gen_gzip_assets.py — DO NOT EDIT.",
        "// Source of truth: the src/*HTML.h / src/Shared*.h string assets.",
        "// FIRMWARE_VERSION baked in at generation: %s" % version,
        "#include <Arduino.h>",
        "#include <pgmspace.h>",
        "",
    ]
    for name, gz in assets:
        body = ",".join("0x%02x" % b for b in gz)
        # 16 bytes per line for readability
        chunks = [",".join("0x%02x" % b for b in gz[i:i + 16])
                  for i in range(0, len(gz), 16)]
        arr = ",\n  ".join(chunks)
        lines.append("static const uint8_t %s_GZ[] PROGMEM = {" % name)
        lines.append("  %s" % arr)
        lines.append("};")
        lines.append("static const size_t %s_GZ_LEN = %d;" % (name, len(gz)))
        lines.append("")
    return "\n".join(lines) + "\n"


def write_if_changed(path, content):
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as fh:
            if fh.read() == content:
                return False
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)
    return True


def generate(version):
    assets = collect_assets(version)
    header = render_header(assets, version)
    changed = write_if_changed(OUT_HEADER, header)
    total_gz = sum(len(gz) for _, gz in assets)
    status = "regenerated" if changed else "unchanged"
    print("gzip-assets: %d assets, %d B compressed, v%s (%s)"
          % (len(assets), total_gz, version, status))
    return changed


def version_from_platformio_ini():
    ini = os.path.join(PROJECT_DIR, "platformio.ini")
    with open(ini, "r", encoding="utf-8") as fh:
        m = re.search(r'-DFIRMWARE_VERSION=\\?"([^"\\]+)\\?"', fh.read())
    return m.group(1) if m else "0.0.0-dev"


def version_from_env(env):
    for d in env.get("CPPDEFINES", []):
        if isinstance(d, (list, tuple)) and len(d) == 2 and d[0] == "FIRMWARE_VERSION":
            return str(d[1]).strip().strip('\\"').strip('"')
    return version_from_platformio_ini()


# --- entry points ----------------------------------------------------------
# `Import` is injected into globals by PlatformIO/SCons when this runs as a
# build hook; it's undefined when the file is run directly.
try:
    Import("env")  # noqa: F821
    _UNDER_PLATFORMIO = True
except NameError:
    _UNDER_PLATFORMIO = False

if _UNDER_PLATFORMIO:
    generate(version_from_env(env))  # noqa: F821 — parse errors intentionally fail the build
elif __name__ == "__main__":
    generate(version_from_platformio_ini())
